# Generated by Django 5.0 on 2025-04-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
    ]
