# Generated by Django 5.0 on 2025-04-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0005_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Quantidade comprada'),
        ),
    ]
