# Generated by Django 5.0 on 2025-04-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0006_ingredient_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='brand',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo unitario'),
        ),
    ]
