# Generated by Django 5.0 on 2025-04-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0010_remove_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['category_ingredient'], 'verbose_name': 'Ingredientes'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
    ]
