# Generated by Django 5.0 on 2025-04-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0011_alter_ingredient_options_remove_ingredient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['category_ingredient'], 'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
    ]
