# Generated by Django 5.0 on 2025-04-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0012_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantidade em Estoque'),
        ),
    ]
