# Generated by Django 5.0 on 2025-04-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0013_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sucos.ingredient', verbose_name='Ingrediente'),
            preserve_default=False,
        ),
    ]
