# Generated by Django 5.0 on 2025-04-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0014_product_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
