# Generated by Django 5.0 on 2025-04-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0015_remove_product_brand_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('debito', 'Cartão de Débito'), ('credito', 'Cartão de Crédito')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
