# Generated by Django 5.0 on 2025-04-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucos', '0016_cart_finalizado_cart_finalizado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-finalizado_em'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
